qa: storage_qa network_qa utilities_qa aurora_db_qa efs_qa instance_pool_qa

plan_qa: plan_storage_qa plan_network_qa plan_utilities_qa plan_aurora_db_qa plan_efs_qa plan_instance_pool_qa

refresh_qa: refresh_storage_qa refresh_network_qa refresh_utilities_qa refresh_aurora_db_qa refresh_efs_qa refresh_instance_pool_qa

destroy_qa: destroy_instance_pool_qa destroy_efs_qa destroy_aurora_db_qa destroy_utilities_qa destroy_network_qa destroy_storage_qa

.PHONY: qa destroy_qa refresh_qa plan_qa