#cloud-config
coreos:
  update:
    reboot-strategy: off
  units:
    - name: format-opt-data.service
      command: start
      content: |
        [Unit]
        Description=Formats opt data drive
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Environment="LABEL=opt-data"
        Environment="DEV=/dev/xvdh"
        ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then  wipefs -a -f $DEV && mkfs.ext4 -F -L $LABEL $DEV && echo wiped; fi"
    - name: opt-data.mount
      command: start
      content: |
        [Unit]
        Description=Mount data to /opt/data
        Requires=format-opt-data.service
        After=format-opt-data.service
        [Mount]
        What=/dev/xvdh
        Where=/opt/data
        Type=ext4
    - name: mysql.service
      command: start
      content: |
        [Unit]
        Description=Mysql Service
        Requires=docker.service
        After=docker.service
        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n -p 3306:3306 -e MYSQL_USER="${db_username}" -e MYSQL_ROOT_PASSWORD="${db_password}" -e MYSQL_PASSWORD="${db_password}" -e MYSQL_DATABASE="${db_name}" -v /opt/data/mysql:/var/lib/mysql mysql
        ExecStop=/usr/bin/docker stop %n
        [Install]
        WantedBy=multi-user.target
