instance_pool_global_admiral: etcd_global_admiral docker_registry_global_admiral gocd_global_admiral

plan_instance_pool_global_admiral: plan_etcd_global_admiral plan_docker_registry_global_admiral plan_gocd_global_admiral

refresh_instance_pool_global_admiral: refresh_etcd_global_admiral refresh_docker_registry_global_admiral refresh_gocd_global_admiral

destroy_instance_pool_global_admiral: destroy_gocd_global_admiral destroy_docker_registry_global_admiral destroy_etcd_global_admiral

init_instance_pool_global_admiral: init_global_admiral
	cp -rf $(INFRA_GLOBAL_ADMIRAL)/instance-pool/policy/assume-role-policy.json $(BUILD_GLOBAL_ADMIRAL)/policy;
	cp -rf $(INFRA_GLOBAL_ADMIRAL)/instance-pool/user-data/bootstrap* $(BUILD_GLOBAL_ADMIRAL)/user-data;

.PHONY: instance_pool_global_admiral destroy_instance_pool_global_admiral refresh_instance_pool_global_admiral plan_instance_pool_global_admiral