#cloud-config
coreos:
  update:
    reboot-strategy: off
  units:
    - name: s3sync-tools-portal.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Synchronizes local folder with Module's folder in S3 config bucket
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=/usr/bin/docker pull stakater/s3sync
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
                                  -e S3_BUCKET_LOCATION=${config_bucket_name}/${module_name} \
                                  -v /tools-portal-config:/s3sync \
                                  stakater/s3sync
        ExecStop=/usr/bin/docker stop %n
        RestartSec=30
        Restart=always
    - name: consul-agent.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Consul Agent
        After=docker.service
        Requires=docker.service
        [Service]
        TimeoutStartSec=0
        ExecStartPre=/opt/bin/download-consul-server-ip.sh -b ${config_bucket_name}
        ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment CONSUL_SERVER=$(</consul/server-ip/consul-server-ip)"
        ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment FALLBACK_HOST_DNS=$(nslookup $(hostname -i) | grep 'Server' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')"
        ExecStartPre=/usr/bin/docker pull consul:0.7.1
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
                                  --net="host" \
                                  -e 'CONSUL_ALLOW_PRIVILEGED_PORTS=' \
                                  -v /consul/data:/consul/data \
                                  consul:0.7.1 agent -retry-join=$${CONSUL_SERVER} -dns-port=53 -bind=$private_ipv4 -client=0.0.0.0 -recursor=$${FALLBACK_HOST_DNS}
        ExecStop=/usr/bin/docker stop %n
        RestartSec=650
        Restart=always
    - name: registrator.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Registrator, Registers running docker containers with consul
        After=docker.service
        Requires=docker.service
        After=consul-agent.service
        Requires=consul-agent.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=/usr/bin/docker pull gliderlabs/registrator:latest
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStartPre=-/usr/bin/sleep 10
        ExecStart=/usr/bin/docker run --rm --name %n \
                                  --net "host" \
                                  -v /var/run/docker.sock:/tmp/docker.sock \
                                  gliderlabs/registrator:latest consul://localhost:8500
        ExecStop=/usr/bin/docker stop %n
        RestartSec=660
        Restart=always
    - name: nginx.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Nginx
        Requires=docker.service
        Requires=consul-agent.service
        After=consul-agent.service

        [Service]
        ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment HOSTNAME=$(hostname -i)"
        ExecStartPre=/usr/bin/docker pull stakater/nginx-with-consul-template:0.18.0-rc1
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
                                  -v /tools-portal-config/nginx/consul-templates:/templates \
                                  -p 80:80 \
                                  --dns=$${HOSTNAME} \
                                  --dns-search=service.consul \
                                  -l SERVICE_NAME=nginx \
                                  stakater/nginx-with-consul-template:0.18.0-rc1
        ExecStop=/usr/bin/docker stop %n
        RestartSec=30
        Restart=always

write_files:
  - path: /opt/bin/download-consul-server-ip.sh
    permissions: 0700
    owner: root
    content: |
        #!/bin/bash
        # This script download a file with consul server's ip from s3
        BUCKET_NAME=""
        bOptionFlag=false;
        # Get options from the command line
        while getopts ":b:" OPTION
        do
            case $OPTION in
                b)
                  BUCKET_NAME=$OPTARG
                  bOptionFlag=true;
                  ;;
                *)
                  echo "Usage: $(basename $0) -b <Name of Bucket to download the file from>"
                  exit 1
                  ;;
            esac
        done

        if ! $bOptionFlag
        then
          echo "Usage: $(basename $0) -b <Name of Bucket to download the file from>"
          exit 1;
        fi

        sudo mkdir -p /consul/server-ip
        docker run --rm -v /consul/server-ip:/aws stakater/aws-cli aws s3 cp s3://$BUCKET_NAME/consul/consul-server-ip .